# Generated by Django 6.0.6 on 2026-06-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_bio_cv_bio_image_bio_linkedin_bio_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
